[build-system]
requires = ["setuptools==80.9.0", "setuptools-scm==10.2.3"]
build-backend = "setuptools.build_meta"

[project]
name = "biomero-shallower"
dynamic = ["version"]
description = "Filesystem normalization of BIOMERO returned OME-Zarr"
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
license-files = ["LICENSE"]
dependencies = ["biomero-schema>=0.2.1b1,<0.4", "numpy>=1.26.4,<3"]

[project.urls]
Repository = "https://github.com/NL-BioImaging/BIOMERO.shallower"
Documentation = "https://nl-bioimaging.github.io/BIOMERO.shallower/"

[project.optional-dependencies]
identity = ["iscc-bio[ome-zarr]==0.2.0"]
test = ["pytest==8.4.2"]

[project.scripts]
biomero-shallower = "biomero_shallower.cli:main"

[tool.setuptools.packages.find]
include = ["biomero_shallower*"]

[tool.setuptools_scm]
version_file = "biomero_shallower/_version.py"
